linters:
  enable:
    - gofmt
    - golint
    - govet
    - errcheck
    - staticcheck
    - gosimple
    - ineffassign

run:
  deadline: 5m
  tests: true
  skip-dirs:
    - vendor/

issues:
  exclude-use-default: false
  max-per-linter: 0
  max-same-issues: 0

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
